# site settings
title: Trail Mix
email: youhoo1234@gmail.com
description: "Honestly, I have no clue what I'm doing, but I keep on doing."
author: anonymous axolotl
baseurl: "/blog"
url: "http://anonymousaxolotl.github.io"
timezone: America/New_York
source: C:\Users\anony\Documents\blog
gems: [jekyll-paginate-v2]
exclude:
  - Gemfile
  - Gemfile.lock
#build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
include: ['_pages']
pagination:
  enabled: false
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# i actually dont know what this is but ive been told its useful
sass:
  sass_dir: assets/css
  style: :nested
