# site settings
title: Hannah Kirkland
email: youhoo1234@gmail.com
description: "I'm an electrical engineering student."
author: Hannah Kirkland
baseurl: "/blog"
url: "http://anonymousaxolotl.github.io"
timezone: America/New_York
source: C:\Users\anony\Documents\blog
plugins_dir:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
#build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
include: ['_pages']

# i actually dont know what this is but ive been told its useful
sass:
  sass_dir: assets/css
  style: :nested
